version: '3.8'

services:
  php:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - /var/www/html/vendor/
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d