version: '3'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
